"""initial

Revision ID: 369d74564f88
Revises: None
Create Date: 2015-10-21 22:51:21.433816

"""

# revision identifiers, used by Alembic.
revision = '369d74564f88'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
