"""second

Revision ID: 543f6fc9ac20
Revises: 369d74564f88
Create Date: 2015-10-21 22:57:51.562247

"""

# revision identifiers, used by Alembic.
revision = '543f6fc9ac20'
down_revision = '369d74564f88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('label', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'label')
    ### end Alembic commands ###
